name: Build and Deploy with Preview URL

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the Node.js version compatible with your project

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel --yes --token ${{ secrets.VERCELTOKEN }} -m githubCommitSha=${{ github.sha }} -m githubCommitAuthorName=${{ github.actor }} -m githubCommitAuthorLogin=${{ github.actor }} -m githubDeployment=1 -m githubOrg=${{ github.repository_owner }} -m githubRepo=${{ github.event.repository.name }} -m githubCommitOrg=${{ github.repository_owner }} -m githubCommitRepo=${{ github.event.repository.name }} -m githubCommitMessage="${{ github.event.head_commit.message }}"
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"  # Optional, increases memory limit for the Node process

      - name: Capture Vercel preview URL
        id: capture_vercel_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCELTOKEN }}
        run: |
          npm install -g vercel
          VERCEL_URL=$(npx vercel --prod --token $VERCEL_TOKEN 2>&1 | tee /dev/tty | grep -o 'https://[a-zA-Z0-9.-]*')
          echo "VERCEL_URL=$VERCEL_URL" >> $GITHUB_ENV

      - name: Post Preview URL as Comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ITHUB_TOKEN }}
          script: |
            const vercelUrl = process.env.VERCEL_URL;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview URL: ${vercelUrl}`
            });
