name: Build and Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with :
        node-version: '16' 

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Update to use Node.js 16

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCELTOKEN }}
