name: Build and Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Change working directory
      run: cd /home/runner/work/react_project/react_project/my-react-app

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version you want to use

    - name: Update npm
      run: npm install -g npm@6  # Use npm version 6

    - name: Install dependencies
       working-directory: /home/runner/work/react_project/react_project/my-react-app
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCELTOKEN }}  # Use the secret VERCELTOKEN from GitHub Secrets
